### ISSUE TITLE
PG PLOT Mac

### ISSUE THREAD

**Issue by mpardo1** [scottransom/presto#149]
I have install PGPLOT in my MAc and its not working the demo:
celsaaraujobarja@macbook-pro-de-celsa ~ % /opt/local/share/pgplot/examples/pgdemo2
 Graphics device/type (? to see list, default /Xserve): Xserve
 %PGPLOT, Device type omitted
 %PGPLOT, Invalid device specification: Xserve
 Graphics device/type (? to see list, default /Xserve): Xserve
 %PGPLOT, Device type omitted
 %PGPLOT, Invalid device specification: Xserve
 Graphics device/type (? to see list, default /Xserve):

**Comment by scottransom** [comment]
Try using "/xwin" (and note that the "/" is important!).  If that works, then try "/xserve"

**Comment by mpardo1** [comment]
Still not working

Graphics device/type (? to see list, default /Xserve): /xwin
PGPLOT /xw: cannot connect to X server [localhost:0.0]
 Graphics device/type (? to see list, default /Xserve): /Xserve
PGPLOT /xw: cannot connect to X server [localhost:0.0]

**Comment by scottransom** [comment]
It looks like you don't have an x-server installed.  Did you install PGPLOT from scratch?  If so, I'd recommend using a package manager for Mac so that it automatically installs an X-server as well.  Note that this doesn't seem to be a PRESTO issue, so I'm going to close this issue.  (since PGPLOT isn't part of PRESTO)

**Comment by 0xCoto** [comment]
@scottransom Looks like I'm having a similar issue trying to run `prepfold` with Docker:
```bash
PGPLOT /xw: cannot connect to X server []
 %PGPLOT, PGPAP: no graphics device has been selected
 %PGPLOT, PGPAGE: no graphics device has been selected
 %PGPLOT, PGBBUF: no graphics device has been selected
 %PGPLOT, PGQCF: no graphics device has been selected
 %PGPLOT, PGQCI: no graphics device has been selected
 %PGPLOT, PGQLW: no graphics device has been selected
 %PGPLOT, PGQCH: no graphics device has been selected
 %PGPLOT, PGSCF: no graphics device has been selected
 %PGPLOT, PGSCI: no graphics device has been selected
 %PGPLOT, PGSLW: no graphics device has been selected
 %PGPLOT, PGSCH: no graphics device has been selected
 %PGPLOT, GRTEXT - no graphics device is active.
 %PGPLOT, PGSCF: no graphics device has been selected
 %PGPLOT, PGSCI: no graphics device has been selected
 %PGPLOT, PGSLW: no graphics device has been selected
 %PGPLOT, PGSCH: no graphics device has been selected
 %PGPLOT, PGEBUF: no graphics device has been selected
 %PGPLOT, PGSLW: no graphics device has been selected
 %PGPLOT, PGSCH: no graphics device has been selected
 %PGPLOT, PGSVP: no graphics device has been selected
 %PGPLOT, PGSWIN: no graphics device has been selected

Error in gen_fvect(): Cannot allocate memory
```

(The error persists even after allocating more resources/memory)

It seems like it struggles displaying the plot, which makes sense given I'm running everything from a terminal (with no graphics whatsoever). Does `prepfold` support some kind of option to simply output the result as a `.png` file instead of trying to open it up/directly view it?

**Comment by scottransom** [comment]
You can try using "-noxwin" with `prepfold`.  Depending on exactly how PGPLOT was installed, that should give you the plots you need (as .ps and .png files).

**Comment by 0xCoto** [comment]
The `.png` is still blank, but the `.ps` works, so that's good. Thanks!

**Comment by scottransom** [comment]
Does your Docker image include Latex2html?  If so, the routine `pstoimg` from it is what PRESTO uses to convert .ps files into nice .png versions.
