### ISSUE TITLE
Remove the Pusar Miner in FAQ

### ISSUE THREAD

**Issue by joezhouchenye** [scottransom/presto#185]
Pulsar Miner is using Python 2.7 and Presto is using Python >= 3.7. It's a little confusing as I tried to use Pulsar Miner and installed Python 2.7, but find out it's a total waste of time.

**Comment by scottransom** [comment]
I certainly don't want to remove Pulsar Miner from the FAQ.  Because it is being used by quite a few people and finding pulsars (you can always install an earlier version of PRESTO).  But much better would be to help Alessandro Ridolfi port Pulsar Miner to Python3+!  That's not hard to do at all, and would probably be appreciated.

**Comment by alex88ridolfi** [comment]
Hi @joezhouchenye and @scottransom . PULSAR_MINER has already been ported to Python 3 and is compatible with PRESTO 3+!
Just, I haven't released it publicly because I wanted to also include a number of new functionalities (currently under test) with the overhauled version.
Given that it's taking much more time than I was expecting (sorry!), I'll release the Python3 version now, and add the new functionalities in the next release.
I'll keep you posted!

**Comment by scottransom** [comment]
Great news!  I did 30min of work on PULSAR_MINER this morning and almost have it working in Python3 myself!

**Comment by joezhouchenye** [comment]
Thanks, that's great!
