### ISSUE TITLE
Determining prepfold P and Pdot step sizes

### ISSUE THREAD

**Issue by k-perez** [scottransom/presto#202]
I'd like to understand the exact range over which prepfold conducts a search on. When running prepfold, a grid search is generated across DMs, periods, and p-dots (Example from output file: `> Searching 385 DMs, 257 periods, and 257 p-dots...`)

I understand the step size and factor for each (DM, P, and P-dot) varies depending on what flag is being used (-coarse, -fine, or none). The DM step size is simple. But what exactly does a step size of 1,2,3, etc. mean for P and P-dot? In the example above, say, for a period of 10 seconds, and a pdot of 3e-11, what would the range of the 257 periods and p-dots be? What are the units of the step sizes? Thank-you.

**Comment by scottransom** [comment]
I just added a new section to the FAQ to answer this question, since it has been asked before by several other people.  Please let me know if you have questions!

https://github.com/scottransom/presto/blob/master/FAQ.md#how-does-prepfold-decide-on-the-step-sizes-and-ranges-of-dm-period-and-p-dot-to-search

**Comment by scottransom** [comment]
For your specific numerical question, I can't answer unless you also tell me the duration of the observation $T$.  But the units of the steps are the same units for p and p-dot (i.e seconds and sec/sec, or unitless).

**Comment by k-perez** [comment]
Thanks! The duration of the observations is 1 hr long. Going through an example would be useful. For the example above, if we assume a step size of 1, does this mean a period of 10 seconds and pdot of 3e-11 would go through a grid search spanning -247 to 267 seconds, and -254e-11 to 260e-11 s/s? This does not sound right..

**Comment by scottransom** [comment]
You have to change to frequency rather than use periods.  That's because the phase equation in the writeup is based on frequency.  So for example, if we wanted to search to +/-1 phase wrap of the P=10s pulsar over a 1 hour observation (T), and you had (let's say) N=100 bins in your pulse profile.  Then each step (which corresponds to a drift of a single profile bin over the observation) would be a perturbation of:

delta freq = delta phi / T = ((1/N) / T) = 0.01 / 3600.0 s = 2.77e-6 Hz.

The center frequency is f = 1/P = 1/10 = 0.1 Hz.

And so if we searched from -1 to +1 phase wrap it would be from:  0.1 Hz - 100 * 2.77e-6 Hz to 0.1 Hz + 100 * 2.77-6 Hz.

For the step sizes in f-dot, it is similar:  delta fdot = 2 * delta phi / (T^2) = 0.02 / (3600^2) = 1.5e-9 Hz/s

The central fdot is fd = -pd/(p*p) = -3e-11/(10*10)  = -3e-13 Hz/s

And so the +/- 1 phase wrap search range would be: -3e-13 Hz/s - 100 * 1.5e-9 Hz/s to -3e-13 Hz/s + 100 * 1.5e-9 Hz/s.

Note that the delta freq and delta fdot equations I use above come directly from the formula that I put in the writeup.

**Comment by k-perez** [comment]
Thanks! This makes a lot of sense. How do we know the number of phase wraps for each (-coarse, -fine, or none)? Is this defined by `npfact`? So number of rotations == number of full phase wraps?

**Comment by scottransom** [comment]
yes, that's correct.
