### ISSUE TITLE
prepdata and prepsubband have problems with large .dat files

### ISSUE THREAD

**Issue by paulray** [scottransom/presto#50]
prepdata crashes when the output number of bins in the .dat file exceeds the maximum value for an int32  of 2,147,483,647 bins.  prepsubband may complete, but ends up writing a .inf file with a negative number of bins.

Also, the command-line interpreter can not take a -numout value that large either.

These two issues are independent.

**Comment by scottransom** [comment]
I looked into this a bit yesterday, @paulray.  The command-line issue is a simple fit for 64-bit machines but would be *much* more difficult to fix for 32-bit machines.  I will make the fix for the 64-bit ones and I doubt we'll run into the issue for 32-bit users (we haven't yet in the first ~12 years of PRESTO use!).  And the first one should be easy to fix as well....

**Comment by scottransom** [comment]
I just pushed up a fix for this issue for prepdata, prepsubband, and mpiprepsubband.  Please test it on that new GBT data, @paulray!
